### ISSUE TITLE
Document the build instructions

### ISSUE THREAD

**Issue by hardBSDk** [mvdnes/rboy#18]

**Comment by mvdnes** [comment]
Can you please explain what you think that needs to be documented? Running `cargo run --release` should be all you need.

**Comment by hardBSDk** [comment]
It can be just `cargo run --release`, thanks.

**Comment by mvdnes** [comment]
The [README](https://github.com/mvdnes/rboy/blob/c5ea0c5806e7907ace6c5f349ea7a6c3e732b894/README.md#L10-L13) already states build instructions. Can you clarify what is not clear?

**Comment by mvdnes** [comment]
I have updated the README, hopefully it is more clear.
