### ISSUE TITLE
Cartridge checksum is invalid

### ISSUE THREAD

**Issue by jcs090218** [mvdnes/rboy#26]
I'm beginner want to learn more about emulator. 🤔 

I tried inputting the file `Pokemon - Emerald Version (USA, Europe).gba` but got the following error:

```
Cartridge checksum is invalid
```

I got the file from https://r-roms.github.io/megathread/popular/.

FYI, `roms/cpu_instrs.gb` does work!

Can you explain what went wrong? Does that mean the ROM isn't compatible with the emulator? Thanks!

**Comment by mvdnes** [comment]
Hi, and welcome!

Yes, in this case the game is indeed incompatible. Pokémon Emerald is a Gameboy Advance game, while this emulator only supports the original Gameboy and Gameboy Color games.

The checksum being invalid is generally a good indication something is wrong. (I myself sometimes forget to unzip the ROM for example.) If in some other case you _do_ think the ROM should be compatible, you can always try the emulator with the option `--skip-checksum`.

**Comment by jcs090218** [comment]
Ah, thank you for your clear explanation! :D
