### ISSUE TITLE
Sound BlipBufs are created with sample_rate as its "sample_count" parameter.

### ISSUE THREAD

**Issue by Altaflux** [mvdnes/rboy#27]
I believe that when Blip Blufs are being created the sample rate is being incorrectly used as the "sample_count" parameter.
Although this does not causes any errors it creates BlipBufs which are unnecessarily big in size  as the buffer the same size as the sample rate which only need to contain enough space to hold the OUTPUT_SAMPLE_COUNT.

https://github.com/mvdnes/rboy/blob/main/src/sound.rs#L711

The correct usage would be to pass the "OUTPUT_SAMPLE_COUNT + 1" as a parameter when initializing the BlipBuf.
I am not really sure why the +1 is needed.

**Comment by mvdnes** [comment]
Thank you! :+1: 
I have resolved this in dbf75f8.
