### ISSUE TITLE
Get an explanation

### ISSUE THREAD

**Issue by gil0mendes** [mvdnes/rboy#3]
Hey,

I'm trying learn more about emulators and how the things works on low level... I find this function on your code...

```rust
fn alu_add16imm(&mut self, a: u16) -> u16 {
  let b = self.fetchbyte() as i8 as i16 as u16;
  self.reg.flag(N, false);
  self.reg.flag(Z, false);
  self.reg.flag(H, (a & 0x000F) + (b & 0x000F) > 0x000F);
  self.reg.flag(C, (a & 0x00FF) + (b & 0x00FF) > 0x00FF);
  return a.wrapping_add(b)
}
```

Why this can't add the b directly to a? Without make 3 casts to i8 -> i16 and finally u16?

Thank you in advance 😉

**Comment by gil0mendes** [comment]
Ok... I figured it out!

That operation is needed to don't lost the signal bits.

**Comment by mvdnes** [comment]
Exactly! :+1:

**Comment by gil0mendes** [comment]
Tks 😉
