### ISSUE TITLE
How to run it, try it out

### ISSUE THREAD

**Issue by yaobo-lab** [mvdnes/rboy#30]
Can you give me an example to get me running? Thank you very much！

 I run it：

`rboy.exe filename=cpu_instrs.gb.gz  --test-mode`

is show a error：

![image](https://github.com/user-attachments/assets/ab62593d-b1e2-42fe-8441-7a31953fbb0d)

**Comment by mvdnes** [comment]
The cpu_instrs ROM is compressed. You need to unpack it first, for example with 7-zip.

After extracting, just run `rboy.exe cpu_instrs.gb`. If you want to know what the other instructions do, see the README, or `rboy.exe --help`.

**Comment by yaobo-lab** [comment]
thx
