### ISSUE TITLE
Clarify buttons to press

### ISSUE THREAD

**Issue by jens1o** [mvdnes/rboy#5]
Could you please add some kind of documentation which keyboard keys are responsible for which gameboy keys? Thanks! I love this emulator, but this makes it hard to recommend it to others. :)

**Comment by jens1o** [comment]
In particular, it was unclear to me what the `Y` key is. Then, I stumbled over the American keyboard layout and found out that `Z` is what I wanted. Perhaps make it possible to recognize the keyboard layout(or support changing the keyboard bindings).

**Comment by jens1o** [comment]
Could you point me to the location where those keybindings are defined?

**Comment by mvdnes** [comment]
The general bindings can be found [here](https://github.com/mvdnes/rboy/blob/27a2b8751390efce165938a306ea55ceb9d603e0/src/main.rs#L135-L150) and those that map to the emulator [here](https://github.com/mvdnes/rboy/blob/27a2b8751390efce165938a306ea55ceb9d603e0/src/main.rs#L181-L194).
